# Example configuration for zmq-nats-bridge

# Global ZMQ settings
[zmq]
# If no message is received within heartbeat * 2, log a warning.
# Publisher should send data frequently enough or implement its own keepalives.
# Value uses humantime format (e.g., "5s", "1m")
heartbeat = "5s"

# Global NATS settings (optional credentials)
[nats]
# user = "my_user"
# password = "my_password"

# Define one or more forwarding mappings
[[forward_mappings]]
# Optional name for easier logging/identification
name = "FuturesTicks"
# List of ZMQ PUB endpoints to connect to (SUB socket)
zmq_endpoints = ["tcp://192.168.6.7:1402"]
# List of ZMQ topics to subscribe to
zmq_topics = ["data/api/Tick"]
# NATS server URI for this mapping
nats_uri = "nats://localhost:4222"
# Target NATS subject to publish messages to
nats_subject = "market_data.FUT_CN.tick"

# Example 2: Forwarding Future 1m Bars
[[forward_mappings]]
name = "FuturesBars1m"
zmq_endpoints = ["tcp://192.168.6.7:1422"]
zmq_topics = ["data/api/Bar"]
nats_uri = "nats://localhost:4222"
nats_subject = "market_data.FUT_CN.bar.1m"

# Example 3: Forwarding Stock Ticks
[[forward_mappings]]
name = "StockTicks"
zmq_endpoints = ["tcp://192.168.6.7:25121"]
zmq_topics = ["data/api/Tick"]
nats_uri = "nats://localhost:4222"
nats_subject = "market_data.STK_CN.tick"

# Example 4: Forwarding Stock 1m Bars
[[forward_mappings]]
name = "StockBars1m"
zmq_endpoints = ["tcp://192.168.6.7:6120"]
# Note: Original README listed "data/api/Tick" here, might need verification
zmq_topics = ["data/api/Bar"]              # Assuming Bar based on NATS subject
nats_uri = "nats://localhost:4222"
nats_subject = "market_data.STK_CN.bar.1m"

# Logging configuration
[logging]
# Console logging settings
[logging.console]
# Enable or disable console logging
enabled = true
# Log level for console: trace, debug, info, warn, error
level = "info"
# Enable ANSI colors in console output
colors = true

# File logging settings
[logging.file]
# Enable or disable file logging
enabled = false
# Log level for file: trace, debug, info, warn, error
level = "info"
# Path to the log file
path = "logs/zmq-nats-bridge.log"
# Whether to append to existing log file or create new one
append = true
