# ZMQ-NATS Bridge Configuration
# Environment variables can be used with ${VAR_NAME} syntax

# Forward mappings define how messages flow from ZMQ to NATS
forward_mappings:
  # Example: Futures Market Data
  - name: "FuturesMarketData"
    desc: "Forward futures market data from ZMQ to NATS"
    enable: false

    # ZMQ Configuration
    zmq:
      endpoints:
        - "tcp://192.168.6.7:1402"
        - "tcp://192.168.6.7:1422"
      topics:
        - "data.api.Tick"
        - "data.api.Bar"
      heartbeat: "30s" # Optional, defaults to no heartbeat if not specified

    # NATS Configuration
    nats:
      uris:
        - "nats://localhost:4222"
      # Credentials from environment variables
      user: "${NATS_USER}"
      password: "${NATS_PASSWORD}"

    # Topic to Subject Mapping Rules
    topic_mapping:
      # Optional prefix for all NATS subjects
      # Format: {source}.{instance}.{protocol}
      subject_prefix: "zmq.line1.pb"

      # Topic transformation rules applied in sequence
      topic_transforms:
        # Replace path separators with dots (e.g., 30s/CZCE/SH601 -> 30s.CZCE.SH601)
        - pattern: "/"
          replacement: "."

        # Replace dots with hyphens (e.g., data.api.Bar -> data-api-bar)
        - pattern: "."
          replacement: "-"

    # Example mappings (for documentation)
    # Original ZMQ topic -> Transformed NATS subject
    # data.api.Bar/30s/CZCE/SH601 -> zmq.line1.pb.data-api-Bar.30s.CZCE.SH601
    # data.api.Tick/SHSE/688176 -> zmq.line1.pb.data-api-tick.SHSE.688176

  # Example: Stock Market Data
  - name: "StockMarketData"
    desc: "Forward stock market data from ZMQ to NATS"
    enable: false

    zmq:
      endpoints:
        - "tcp://192.168.6.7:25121"
        - "tcp://192.168.6.7:6120"
      topics:
        - "data.api.Tick"
        - "data.api.Bar"
      heartbeat: "30s"

    nats:
      uris:
        - "nats://localhost:4222"
      user: "${NATS_USER}"
      password: "${NATS_PASSWORD}"

    topic_mapping:
      subject_prefix: "zmq.line1.pb"
      topic_transforms:
        - pattern: "/"
          replacement: "."

        - pattern: "."
          replacement: "-"

  # Test ZMQ Publisher for local testing
  - name: "TestZmqPublisher"
    desc: "Forward test messages from local ZMQ publisher to NATS"
    enable: true

    zmq:
      endpoints:
        - "tcp://127.0.0.1:5555"
      topics:
        - "data.api.Tick"
        - "data.api.Bar"
      heartbeat: "30s"

    nats:
      uris:
        - "nats://localhost:4222"
      user: "${NATS_USER}"
      password: "${NATS_PASSWORD}"

    topic_mapping:
      subject_prefix: "zmq.test.txt"
      topic_transforms:
        - pattern: "/"
          replacement: "."
        - pattern: "."
          replacement: "-"

# Logging Configuration
logging:
  console:
    enabled: true
    level: "debug"
    colors: true

  file:
    enabled: false
    level: "info"
    path: "logs/zmq-nats-bridge.log"
    append: true

